package com.bluewise.model;

public class BaIcd10 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BA_ICD10.BM
     *
     * @mbggenerated
     */
    private String BM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BA_ICD10.MC
     *
     * @mbggenerated
     */
    private String MC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BA_ICD10.PYM
     *
     * @mbggenerated
     */
    private String PYM;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BA_ICD10.BM
     *
     * @return the value of BA_ICD10.BM
     *
     * @mbggenerated
     */
    public String getBM() {
        return BM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BA_ICD10.BM
     *
     * @param BM the value for BA_ICD10.BM
     *
     * @mbggenerated
     */
    public void setBM(String BM) {
        this.BM = BM == null ? null : BM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BA_ICD10.MC
     *
     * @return the value of BA_ICD10.MC
     *
     * @mbggenerated
     */
    public String getMC() {
        return MC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BA_ICD10.MC
     *
     * @param MC the value for BA_ICD10.MC
     *
     * @mbggenerated
     */
    public void setMC(String MC) {
        this.MC = MC == null ? null : MC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BA_ICD10.PYM
     *
     * @return the value of BA_ICD10.PYM
     *
     * @mbggenerated
     */
    public String getPYM() {
        return PYM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BA_ICD10.PYM
     *
     * @param PYM the value for BA_ICD10.PYM
     *
     * @mbggenerated
     */
    public void setPYM(String PYM) {
        this.PYM = PYM == null ? null : PYM.trim();
    }
}