package com.bluewise.model;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_ID
     *
     * @mbggenerated
     */
    private String USER_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USERNAME
     *
     * @mbggenerated
     */
    private String USERNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PASSWORD
     *
     * @mbggenerated
     */
    private String PASSWORD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NAME
     *
     * @mbggenerated
     */
    private String NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.RIGHTS
     *
     * @mbggenerated
     */
    private String RIGHTS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ROLE_ID
     *
     * @mbggenerated
     */
    private String ROLE_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LAST_LOGIN
     *
     * @mbggenerated
     */
    private String LAST_LOGIN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.IP
     *
     * @mbggenerated
     */
    private String IP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.STATUS
     *
     * @mbggenerated
     */
    private String STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.BZ
     *
     * @mbggenerated
     */
    private String BZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.SKIN
     *
     * @mbggenerated
     */
    private String SKIN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EMAIL
     *
     * @mbggenerated
     */
    private String EMAIL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NUMBER
     *
     * @mbggenerated
     */
    private String NUMBER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PHONE
     *
     * @mbggenerated
     */
    private String PHONE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_ID
     *
     * @return the value of sys_user.USER_ID
     *
     * @mbggenerated
     */
    public String getUSER_ID() {
        return USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_ID
     *
     * @param USER_ID the value for sys_user.USER_ID
     *
     * @mbggenerated
     */
    public void setUSER_ID(String USER_ID) {
        this.USER_ID = USER_ID == null ? null : USER_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USERNAME
     *
     * @return the value of sys_user.USERNAME
     *
     * @mbggenerated
     */
    public String getUSERNAME() {
        return USERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USERNAME
     *
     * @param USERNAME the value for sys_user.USERNAME
     *
     * @mbggenerated
     */
    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME == null ? null : USERNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PASSWORD
     *
     * @return the value of sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PASSWORD
     *
     * @param PASSWORD the value for sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NAME
     *
     * @return the value of sys_user.NAME
     *
     * @mbggenerated
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NAME
     *
     * @param NAME the value for sys_user.NAME
     *
     * @mbggenerated
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.RIGHTS
     *
     * @return the value of sys_user.RIGHTS
     *
     * @mbggenerated
     */
    public String getRIGHTS() {
        return RIGHTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.RIGHTS
     *
     * @param RIGHTS the value for sys_user.RIGHTS
     *
     * @mbggenerated
     */
    public void setRIGHTS(String RIGHTS) {
        this.RIGHTS = RIGHTS == null ? null : RIGHTS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ROLE_ID
     *
     * @return the value of sys_user.ROLE_ID
     *
     * @mbggenerated
     */
    public String getROLE_ID() {
        return ROLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ROLE_ID
     *
     * @param ROLE_ID the value for sys_user.ROLE_ID
     *
     * @mbggenerated
     */
    public void setROLE_ID(String ROLE_ID) {
        this.ROLE_ID = ROLE_ID == null ? null : ROLE_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LAST_LOGIN
     *
     * @return the value of sys_user.LAST_LOGIN
     *
     * @mbggenerated
     */
    public String getLAST_LOGIN() {
        return LAST_LOGIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LAST_LOGIN
     *
     * @param LAST_LOGIN the value for sys_user.LAST_LOGIN
     *
     * @mbggenerated
     */
    public void setLAST_LOGIN(String LAST_LOGIN) {
        this.LAST_LOGIN = LAST_LOGIN == null ? null : LAST_LOGIN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.IP
     *
     * @return the value of sys_user.IP
     *
     * @mbggenerated
     */
    public String getIP() {
        return IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.IP
     *
     * @param IP the value for sys_user.IP
     *
     * @mbggenerated
     */
    public void setIP(String IP) {
        this.IP = IP == null ? null : IP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.STATUS
     *
     * @return the value of sys_user.STATUS
     *
     * @mbggenerated
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.STATUS
     *
     * @param STATUS the value for sys_user.STATUS
     *
     * @mbggenerated
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.BZ
     *
     * @return the value of sys_user.BZ
     *
     * @mbggenerated
     */
    public String getBZ() {
        return BZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.BZ
     *
     * @param BZ the value for sys_user.BZ
     *
     * @mbggenerated
     */
    public void setBZ(String BZ) {
        this.BZ = BZ == null ? null : BZ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.SKIN
     *
     * @return the value of sys_user.SKIN
     *
     * @mbggenerated
     */
    public String getSKIN() {
        return SKIN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.SKIN
     *
     * @param SKIN the value for sys_user.SKIN
     *
     * @mbggenerated
     */
    public void setSKIN(String SKIN) {
        this.SKIN = SKIN == null ? null : SKIN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.EMAIL
     *
     * @return the value of sys_user.EMAIL
     *
     * @mbggenerated
     */
    public String getEMAIL() {
        return EMAIL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.EMAIL
     *
     * @param EMAIL the value for sys_user.EMAIL
     *
     * @mbggenerated
     */
    public void setEMAIL(String EMAIL) {
        this.EMAIL = EMAIL == null ? null : EMAIL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NUMBER
     *
     * @return the value of sys_user.NUMBER
     *
     * @mbggenerated
     */
    public String getNUMBER() {
        return NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NUMBER
     *
     * @param NUMBER the value for sys_user.NUMBER
     *
     * @mbggenerated
     */
    public void setNUMBER(String NUMBER) {
        this.NUMBER = NUMBER == null ? null : NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PHONE
     *
     * @return the value of sys_user.PHONE
     *
     * @mbggenerated
     */
    public String getPHONE() {
        return PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PHONE
     *
     * @param PHONE the value for sys_user.PHONE
     *
     * @mbggenerated
     */
    public void setPHONE(String PHONE) {
        this.PHONE = PHONE == null ? null : PHONE.trim();
    }
}